[versions]
agp = "8.13.1"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.0"
navigation = "2.9.6"
preferenceKtx = "1.2.1"
zxing = "3.5.4"
cameraX = "1.5.1"
room = "2.8.4"
lifecycleService = "2.10.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraX" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }

room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-annotations = {group = "androidx.room", name="room-compiler", version.ref = "room"}
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
room-plugin = {id = "androidx.room", version.ref = "room"}