[versions]
agp = "8.13.2"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
navigation = "2.9.6"
preferenceKtx = "1.2.1"
zxing = "3.5.4"
cameraX = "1.5.2"
room = "2.8.4"
lifecycleService = "2.10.0"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockito = "5.21.0"
rules = "1.7.0"
runner = "1.7.0"
espressoContrib = "3.7.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraX" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }

room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-annotations = {group = "androidx.room", name="room-compiler", version.ref = "room"}
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito"}
test-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoContrib" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
room-plugin = {id = "androidx.room", version.ref = "room"}